wordpress:
 image: wordpress
 links:
 - wordpress_db:mysql
 ports:
 - 7070:80
wordpress_db:
 image: mariadb
 environment:
  MYSQL_ROOT_PASSWORD: Password@123
phpadmin:
 image: corbinu/docker-phpmyadmin
 links:
 - wordpress_db:mysql
 ports:
 - 7171:80
 environment:
  MYSQL_USERNAME: userz
  MYSQL_USERZ_PASSWORD: Password@123
